# docker-build.yml - V1.7 (Final, with Monitoring Tools Installed)
name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space and install monitoring tools
        run: |
          echo "--- Installing sysstat for mpstat monitoring... ---"
          sudo apt-get update && sudo apt-get install -y sysstat
          echo "--- Freeing up disk space by removing large, unused toolsets... ---"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          echo "--- Initial Disk and Docker Space ---"
          df -h .
          docker system df

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sjpgwh/text-gen-ui:latest

      - name: Check peak resource usage
        if: always()
        run: |
          echo "--- Peak Disk and Docker Space (after build, before cleanup) ---"
          df -h .
          docker system df
          echo "--- Peak CPU Load (5-second average during build) ---"
          mpstat 5 1

      - name: Clean up Docker resources after build
        if: always()
        run: |
          echo "--- Cleaning up Docker resources... ---"
          docker system prune -f
          echo "--- Final Disk Space (after cleanup) ---"
          df -h .
