# docker-build.yml - V1.5 (Final, with Smart Pre-Build Cleanup)
name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Your self-hosted runner configuration is preserved.
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Selectively frees up disk space on the runner BEFORE the build.
      # This preserves the Docker cache for faster builds and now works without a password prompt.
      - name: Free up disk space on runner
        run: |
          echo "--- Freeing up disk space by removing large, unused toolsets... ---"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          echo "--- Disk space after selective cleanup: ---"
          df -h .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sjpgwh/text-gen-ui:latest

      # Optional but recommended: A final prune AFTER the build to keep the runner tidy for the future.
      - name: Clean up Docker resources after build
        if: always()
        run: |
          echo "--- Cleaning up Docker resources on self-hosted runner... ---"
          docker system prune -f
